### ISSUE TITLE
报告问题

### ISSUE THREAD

**Issue by XuRulin** [SISSORS-FDU/baidu-adblock#1]
最近百度搜索“键盘”广告会稍后出现，导致屏蔽失败

**Comment by zhangyazhong** [comment]
今天我也遇到类似问题了，刚刚更新了一下检测规则，自己测试已经没有问题了

**Comment by XuRulin** [comment]
已经没有问题了，非常棒，感谢作者

**Comment by CodeEncryption** [comment]
现在又遇到这个情况了，今天用百度的时候也出现了类似情况，作者还在维护吗

**Comment by zhangyazhong** [comment]
> 现在又遇到这个情况了，今天用百度的时候也出现了类似情况，作者还在维护吗

诶...是搜索什么词的时候出现问题的，我目前还没有遇到。是加载完页面又新增进去广告还是本来就有没有被删掉

**Comment by CodeEncryption** [comment]
> > 现在又遇到这个情况了，今天用百度的时候也出现了类似情况，作者还在维护吗
> 
> 诶...是搜索什么词的时候出现问题的，我目前还没有遇到。是加载完页面又新增进去广告还是本来就有没有被删掉

我是搜索云服务器的时候出现的，刚刚试了一下还会，搜索后过了差不多一秒钟左右加载广告。

**Comment by zhangyazhong** [comment]
> > > 现在又遇到这个情况了，今天用百度的时候也出现了类似情况，作者还在维护吗
> > 
> > 
> > 诶...是搜索什么词的时候出现问题的，我目前还没有遇到。是加载完页面又新增进去广告还是本来就有没有被删掉
> 
> 我是搜索云服务器的时候出现的，刚刚试了一下还会，搜索后过了差不多一秒钟左右加载广告。

嗯，是我的问题，因为我有在用AdBlock，你讲的那些广告会被AdBlock过滤掉，所以之前没有发现这个问题。嗯...现在改了下，应该可以了。
